[#db-core-design]
= Action Flow Database Design Notes

:reproducible:
:listing-caption: Listing
:source-highlighter: rouge
:toc:
:toc-title: Action Flow Database Design Notes Table of Contents

Author: https://github.com/brick-team[brick-team]

== MySQL Design

MySQL design is based on xref:xml-core-design-zhcn.adoc#xml-design-notes[Action Flow XML Design Notes]. MySQL design divides Action Flow into two parts: . Candidate configurations: Candidate configurations are used to store REST_API, Java_Method, and fetch expression related content to provide the base data for runtime configuration. . Runtime configuration: The runtime configuration is used to store the information required during the execution of the flow. For example, workflow, result information, and fetch information during work.

=== Candidate Configuration

This section describes the design of the candidate configuration, which should have REST_API related information, Java_Method, and fetch expression related information as described in the previous section. The following is the Action-related design first.

Action table structure
|===
| Field Name | Type | Nullable | Comments

|id
|int
|no
|primary key

|type
|type
|no
|1:rest_api,2:java_method

|url
|varchar
|yes
|type=1 for HTTP request address

|method
|varchar
|varchar
|type=1 for HTTP request method (POST\\GET\\\DELETE\\\PUT) type=2 for java function name

|class_name
|varchar
|yes
|type=2 means the full path of the class to be executed

|===

The next is the information of the two kinds of parameters under the action, and the design of the corresponding parameter table of REST_API is as follows:

rest_api_param table structure

|===

|Field Name |Type |Nullable |Comments

|id
|int
|no
|primary key

|action_id
|action_id
|No
|action table association id

|in
|varchar
|yes
|Parameter Location

|name
|varchar
|is
|Name of the parameter

|require
|tinyint
|yes
|Required or not

|value
|varchar
|yes
|Default value

|pid
|int
|yes
|parent id

|===

JAVA_METHOD The corresponding parameter table is designed as follows:


java_method_param table structure

|===
| Field Name | Type | Nullable | Comments

|id
|int
|no
|primary key

|action_id
|action_id
|No
|action table association id

|index
|index
|yes
|The index of the parameter, counting from 0.

|type
|varchar
|no
|Parameter type, class full path

|name
|varchar
|yes
|parameter name

|value
|varchar
|yes
|Default value

|pid
|int
|yes
|parent id
|===

rest_api_result table structure

|===
| Field Name | Type | Nullable | Comments

|id
|int
|no
|primary key

|action_id
|action_id
|No
|action table associated id

|parent_id
|int
|yes
|The parent id can be empty.

|field_name
|varchar
|no
|field_name

|type
|varchar
|no
|Value Type

|value
|varchar
|yes
|field value
|===


In this design, the XML schema does not bind the subordinate tag extract of param directly to the parameter table, such extract tags are considered as runtime configuration and will be given to the executor to set the relevant configuration.

=== Runtime configuration

The runtime configuration is mainly designed around the flow tag, and the data table structure corresponding to the flow tag is as follows.

flow table structure

|===
| Field Name | Type | Nullable | Comments

|id
|int
|no
|primary key

|name
|varchar
|yes
|Workflow Name

|qualifier
|varchar
|yes
|integration with spring
|===

watcher table structure

|===
| Field Name | Type | Nullable | Comments

|id
|int
|no
|primary key

|condition
|varchar
|no
|Conditional expressions

|el_type
|varchar
|no
|Type of expression

|===


Under the flow tag there are also work tag and watcher tag and watcher subordinate cat tag and then tag, the structure is designed as follows

work table structure

|===
| Field Name | Type | Nullable | Comments

|id
|int
|no
|primary key

|action_id
|int
|yes
|action table association id
|===

flow_work table structure

|===
| Field Name | Type | Nullable | Comments

|id
|int
|no
|primary key

|flow_id
|int
|No
|flow table associated id

|step
|varchar
|no
|step value

|work_id
|int
|no
|The associated work table id

|type
|varchar
|yes
|is the top level

|async
|int
|no
|whether it is asynchronous (asynchronous: all subsequent processes are disconnected from it)

|sort
|asynchronous
|no
|sort field (only the top level has it)
|===

flow_watcher table structure

|===
| Field Name | Type | Nullable| Comments

|id
|int
|no
|primary key

|flow_work_id
|int
|yes
|flow_work_table_association_id

|then_or_cat
|varchar
|no
|then or cat node

|next_flow_work_id
|int
|no
|id of the flow_work table

|watcher_id
|int
|no
|The id of the watcher table.

|sort
|sort
|no
|sort field
|sort
|===

The extract tag is bound directly to the param or result table. The data structure is as follows

extract table structure

|===
| Field Name | Type | Nullable | Comments

|id
|int
|no
|primary key

|flow_id
|int
|No
|flow table primary key

|flow_work_id
|int
|no
|flow_work table primary key

|ref_id
|ref_id
|no
|type=1:associated with rest_api_param, type=2:associated with ava_method_param table, type=3:associated with result table

|type
|type
|no
|type=1:associated with rest_api_param, type=2:associated with ava_method_param table, type=3:associated with result table

|step
|varchar
|Yes
|step_tag

|el_type
|varchar
|no
|el takes the value of the expression type

|el
|varchar
|No
|The value of the expression

|===

result table structure

|===
| Field Name | Type | Nullable | Comments

|id
|int
|no
|primary key

|flow_id
|int
|No
|primary_key

|parent_id
|int
|yes
|parent_id can be null


|field_name
|varchar
|no
|field_name

|type
|varchar
|no
|Value Type

|value
|varchar
|yes
|field value
|===


Test data
[source,xml]
----
    <flows
        <flow id="1">
            <work step="1" ref_id="rest_api_1">
                <watcher condition="($.age>10)" elType="">
                    <then
                        <work step="2" ref_id="java_method_1">
                            <watcher condition="true">
                                <then
                                    <work step="6" ref_id="java_method_1"/>

                                </then>
                            </watcher
                        </work
                        <work step="3" ref_id="java_method_1"/>
                    </then>
                    <cat
                        <work step="4" ref_id="java_method_1"/>
                        <work step="5" ref_id="java_method_1"/>
                    </cat
                </watcher>
            </work
        </flow>
    </flows>

----

The flow_work test data is as follows

|===
|id |flow_id |step |ref_id|type

|type
|step1
|step1
|rest_api_1
|top

|2
|step1
|step2
|java_method_1
|non-top level

|3
|step1
|step3
|java_method_1
|non-top level


|4
|step1
|step4
|java_method_1
|non-top level

|5
|step1
|step5
|java_method_1
|non-top level

|6
|1
|step6
|java_method_1
|non-top level
|===


The flow_watcher test data is as follows

|===
|id |flow_work_id |condition |el_type |then_or_cat |next_flow_work_id

|condition
|1
|($.age>10)
|JSON_PATH
|then
|2

|2
|1
|($.age>10)
|JSON_PATH
|then
|3

|4
|1
|($.age>10)
|JSON_PATH
|cat
|4

|5
|1
|($.age>10)
|JSON_PATH
|cat
|5


|6
|2
|true
|JSON_PATH
|then
|6

|===

Steps to use


. Find the data in the flow_work table whose type is top-level
. Loop through the data in the first step and do the following with it
    ... . search for the id of the flow_work table in the flow_watcher table
    ... Execute condition to determine if it matches, and if it does, search the next_flow_work_id data back in the flow_work table, recursive operations 1, 2


After completing the flow execution process design, you also need to configure the execution parameters during execution, which should be bound to the flow_work table with the following table structure


|===
| Field Name | Field Meaning

| id
| primary key

|flow_work_id
|flow_work table id

| action_type
| action_type, rest_api, java_method

| action_param_id
| parameter_table_id

| el
| fetch expression


|===
