[#program-core-design]
= Action Flow program core description


:reproducible:
:listing-caption: Listing
:source-highlighter: rouge
:toc:
:toc-title: Action Flow program core description table of contents


Author: https://github.com/brick-team[brick-team]

Before you can understand the Action Flow program core design instructions, you need to have some understanding of *XML* and **database** design, the related documentation can be found at

* xref:xml-core-design-en.adoc#xml-design-notes[Action Flow XML Design Notes]
* xref:db-core-design-en.adoc#db-core-design[Action Flow database design notes]


== Module Description
The Action Flow project is developed using Maven and JDK8+ with the following Maven module structure.


[source,text]
----
├── action-flow-core: Action Flow core package
├── action-flow-document: Action Flow documentation
├── action-flow-execute: Action Flow executor <1>
├─ action-flow-metrics: Action Flow metrics monitoring
├── action-flow-model: Action Flow model package
├── action-flow-parse: Action Flow parser package
│ ├── action-flow-openapi-parse: Action Flow parsing openapi documentation
│ ├── action-flow-parse-api: Action Flow parsing interface definition
│ ├── action-flow-swagger-parse: Action Flow parses Swagger documentation
│ ├── action-flow-xml-parse: Action Flow parses XML documents
├── action-flow-sample: Action Flow use case application
├── action-flow-spring: Action Flow integration with Spring
├── action-flow-storage: Action Flow storage medium
│ ├── action-flow-mysql-storage: Action Flow uses MySQL as the storage medium
│ ├── action-flow-storage-api: Action Flow storage API
├── action-flow-test: Action Flow test cases
├── action-flow-web: Acton Flow WEB project
│ ├── action-flow-common-web: Action Flow public web
│ ├── action-flow-embedded-web: Action Flow Embedded WEB
│ ├── action-flow-independent-web: Action Flow Independent Deployment WEB
│ ├── action-flow-ui: Action Flow front-end project
----
<1> Action Flow executor is used to execute REST-API, Java-Method, etc. for completing action execution.

== Storage Module
The storage module only supports **in-memory storage** and **database storage** in the current version. The storage module is responsible for managing three core objects



|===
|Core Type |Function  |Java Class| Storage Interface


|action
|behavior action
| `com.github.brick.action.flow.model.execute.ActionExecuteEntity`.
| `com.github.brick.action.flow.storage.api.nv.ActionExecuteEntityStorage`

| result
| result definition
| `com.github.brick.action.flow.model.execute.ResultExecuteEntity`
| `com.github.brick.action.flow.storage.api.nv.ResultExecuteEntityStorage`

| flow
| Execute Flow
| `com.github.brick.action.flow.model.execute.FlowExecuteEntity`
| `com.github.brick.action.flow.storage.api.nv.FlowExecuteEntityStorage`

|===

In actual use action, result and flow three core object execution also need to cooperate with other objects, these dependent objects in principle to different storage patterns to handle themselves, in action-flow-storage-api project allows only the interface definition, not the definition of related methods.



=== In-memory storage
The current version of in-memory storage serves only the file schema, and its core role is to store data information of each Action Flow file. The implementation of data storage in the form of memory is relatively simple, just need to file as the largest group, the different Action Flow file information stored in memory, the storage structure of choice is Map. The following is an illustration of the storage design of the core object flow, the same for the other two, the memory-based storage implementation class is `com.github.brick.action.flow.storage.memory.nv.ResultExecuteEntityMemoryStorage`, the specific implementation code is as follows:

[source,java]
----
public class FlowExecuteEntityMemoryStorage implements FlowExecuteEntityStorage {
    Map<String, Map<Serializable, FlowExecuteEntity>> map = new HashMap<>(32);

    @Override
    public void save(String fileName, List<FlowExecuteEntity> flows) {
        Map<Serializable, FlowExecuteEntity> collect = flows.stream().collect(Collectors.toMap(FlowExecuteEntity::getId, s -> s));
        map.put(fileName, collect);
    }

    @Override
    public FlowExecuteEntity getFlow(String fileName, Serializable flowId) {
        Map<Serializable, FlowExecuteEntity> serializableFlowExecuteEntityMap = map.get(fileName);
        if (serializableFlowExecuteEntityMap == null) {
            throw new IllegalArgumentException("Current file name not resolved, file name = " + fileName);
        }

        FlowExecuteEntity flowExecuteEntity = serializableFlowExecuteEntityMap.get(flowId);
        if (flowExecuteEntity == null) {
            throw new IllegalArgumentException("Data with flowId of " + flowId + " does not exist in the current file name " + fileName + ");
        }
        return flowExecuteEntity;
    }
}
----

The structure used to store the data in the above code is `Map<String, Map<Serializable, FlowExecuteEntity>>` which has the following hierarchical meaning:

. key: Action Flow file name
. value: information about the flow core object in the current Action Flow file, stored using Map.
... key: Unique identifier for the flow
... value: information about the flow object


=== Database Storage
The database storage uses Mybatis as the ORM framework, using Mybatis requires the core solution of two problems.

. mybatis initialization
. mybatis transactions

Mybatis initialization is given to the MysqlConfig class, the specific code is as follows:
[source,java]
----
public class MysqlConfig {
    Class<? >[] mappers = new Class[]{

    };
    private final String user;
    private final String password;
    private final String url;
    private final String dbDriver;

    public MysqlConfig(String user, String password, String url, String dbDriver) {
        this.user = user;
        this.password = password;
        this.url = url;
        this.dbDriver = dbDriver;
        // Initialize MybatisUtils
        MybatisUtil mybatisUtil = new MybatisUtil(user, password, url, dbDriver, mappers);
    }
}
----

During the development phase, you need to place the required Mapper interface in the MysqlConfig#mappers property, so that you only need to build the MysqlConfig object to complete the Mybatis initialization.


Mybatis transactions are handled manually in the MybatisUtil#work method, with the following code.
[source,java]
----
    public static void work(ExecuteMapper executeMapper) throws Exception {

        SqlSession open = open();
        try {
            executeMapper.work(open);
            open.commit();
        } catch (Exception e) {
            open.rollback();
            throw e;
        } finally {
            close(open);
        }
    }

----

In the above code the SqlSession is opened by open and then the functions are executed by the usual `try{} catch{} finally{}`, the commit operation is performed on success, the rollback is performed if there is an exception and finally the close operation is performed.
The work function executed in the ExecuteMapper interface is the actual operation that needs to be executed, if you need to get the Mapper you should do the following:

[source,java]
----
SqlSession session = MybatisUtil.getThreadLocalSqlSession();
PeopleMapper mapper = session.getMapper(PeopleMapper.class);
----

Example of MybatisUtil.
[source,java]
----
   @Test
    public void session() throws Exception {
        MybatisUtil.gen().work(session -> {
            extracted1();
            extracted2();

        });


    }

    private void extracted1() throws Exception {
        SqlSession session = MybatisUtil.getThreadLocalSqlSession();
        PeopleMapper mapper = session.getMapper(PeopleMapper.class);
        mapper.insert(1, "f");
    }

    private void extracted2() throws Exception {
        SqlSession session = MybatisUtil.getThreadLocalSqlSession();

        PeopleMapper mapper = session.getMapper(PeopleMapper.class);
        mapper.insert(1, "2");
        int i = 1 / 0;
    }
----

The above code illustrates that the session method acts as an entry function, which needs to get a MybatisUtil instance via MybatisUtil.gen() and then call the work method to perform the actual business operation. The extracted1 and extracted2 methods are used to perform the actual database operations in these two methods. Since the extracted1 and extracted2 methods are the least granular operations these two methods can be used without focusing on transaction processing, while the session method is used as a federated dispatcher, so the session needs to focus on transaction related processing, so it needs to use the work method provided by MybatisUtil to perform unified transaction processing, i.e. Open SqlSession to perform different mapper operations, commit or rollback, and close SqlSession.


=== Using the Storage Module
The use of the storage module first requires clarification of the timing of the storage generation.

. Action Flow supports XML form configuration, so to improve performance, the parsing of the Action Flow XML file will not be done every time, so the data will be stored after the parsing is done, which allows you to choose between in-memory or database storage, the default is in-memory storage.
. Action Flow supports WEB visualization, which allows either in-memory or database storage, with database storage being the default. Allows modification via `action-flow.storage.type` configuration.

[TIP]
====
For more configuration information see xref:config-zhcn.adoc#action-flow-config[Action Flow configuration description]
====

The following is an introduction to the storage model in XML schema, using XML schema development with in-memory storage by default, the basic constructor is as follows.

[source,java]
----
    ActionFlowXmlContext content = new ActionFlowXmlContext("flow.xml");
----

If the initialization of the Action Flow XML Context is done in the above way the in-memory storage is selected by default, if you need to change the storage mode you need to use the following code.

[source,java]
----
    ActionFlowXmlContext content = new ActionFlowXmlContext(StorageType.MYSQL, "flow.xml");
----




== Parser module

== Executor module

== Web module

== Metrics Monitoring Module

The metrics monitoring module is developed using `metrics-core` technology and monitors the following metrics
