[#xml-design-notes]
= Action Flow XML 设计说明



:reproducible:
:listing-caption: Listing
:source-highlighter: rouge
:toc:
:toc-title: Action Flow XML 设计说明目录


Doc Writer https://github.com/brick-team[brick-team]



在常见的JAVA项目中通常会有以下几个操作来完成某个业务。

. 获取参数。
. 参数转换（组装某个业务方法的参数、RPC请求参数）
. 执行一个动作（函数、RPC调用等）
. 逻辑处理（满足XXX条件执行XXX）
. 组装结果信息

根据上述操作流程先设计出基本XML结构，具体示例如下

[source,xml]
----
<action-flow>
    <actions>
        <action id="rest_api_1" type="rest_api" url="" method="">
            <param in="body" name="" require="true" value="">
                <extract fromAction="" el="" elType=""/>
            </param>

            <param in="header" name="" require="true" value="">
                <extract fromAction="" el="" elType=""/>
            </param>
        </action>
        <action id="java_method_1" type="java_method" className="" method="">
            <param index="0" type="java.lang.String" name="" value=""/>
        </action>
    </actions>

    <results>
        <result flowId="1">
            <fields>
                <field id="111">
                    <fieldName>O1</fieldName>
                    <type>object</type>
                    <extract el="$.name" step="1"/>
                    <properties>
                        <fields>
                            <field>
                                <fieldName>f1</fieldName>
                                <type>String</type>
                                <extract el="" step="" elType=""/>
                            </field>
                            <field>
                                <fieldName>f2</fieldName>
                                <type>object</type>
                                <extract el="" step="" elType=""/>
                                <properties>
                                    <fields>
                                        <field>
                                            <fieldName>f3</fieldName>
                                            <type>String</type>
                                            <extract el="" step="" elType=""/>
                                        </field>
                                        <field>
                                            <fieldName>f4</fieldName>
                                            <type>Integer</type>
                                            <extract el="" step="" elType=""/>
                                        </field>
                                    </fields>
                                </properties>

                            </field>
                        </fields>
                    </properties>
                </field>


            </fields>
        </result>
    </results>

    <flows>
        <flow id="1">
            <work step="1" ref_id="rest_api_1">
                <watcher condition="($.age>10)" elType="">
                    <then>
                        <work step="2" ref_id="java_method_1"/>
                        <work step="3" ref_id="java_method_1"/>
                    </then>
                    <cat>
                        <work step="4" ref_id="java_method_1"/>
                        <work step="5" ref_id="java_method_1"/>
                    </cat>
                </watcher>
            </work>
        </flow>
    </flows>


</action-flow>
----

在 XML 文档中出现了多种标签，后续将对这些标签进行分析。

== Action 标签
action 标签包含多个属性:

. id: 唯一标识
. type: 类型，候选项有 JAVA_METHOD 、 REST_API
. url: 路由地址，type 选择 REST_API 时必填
. method: 请求方式或Java方法名称，type 选择 REST_API 时含义为请求方式(GET、POST、DELETE、PUT) ，type 选择 JAVA_METHOD时含义为Java方法名称
. className: 全类名，type 选择 JAVA_METHOD 时必填

在 action 标签下还包含 param 标签，该标签用于进行参数配置， 当 action 标签的 type 属性为 REST_API 时 param 标签包含如下属性:

. in: 参数所在位置，候选项：body、header、query、formData、urlPath
. name: 参数名称
. require: 是否必填
. value: 请求默认值

上述方案只能够支持默认值相关的参数传递，无法支持从某个 action 中提取数据值或者从字符串中提取，因此设计 extract 标签用于提取参数值，extract包含如下属性。

. fromAction: 数据源自那个 action ， 填写内容为 action 标签的 id 属性。可选填，填写时调用 action 标签流程获取数据再取值，不填写时从 flow 标签执行参数中获取。
. el: 取值表达式，默认采用 JSON_PATH 表达式形式编写。
. elType: 取值表达式类型，项目默认支持 JSON_PATH。


当 action 标签的 type 属性为 JAVA_METHOD 时 param 标签包含如下属性:

. index: 参数索引位置，从0开始计数
. type: 参数类型，java 类全路径。
. name: 参数名称
. value: 请求默认值（字符串表示，如果是复杂类型会通过 GSON 工具反序列化)

Action 标签的作用：定义了一个动作，该动作可以是 REST_API 调用、JAVA函数调用。其中子标签 param 用于定义参数信息，param 标签下存在 extract 标签，extract 标签的作用是用于从某个 Action 标签执行后得到数据作为当前 Action 标签的执行参数。

== Result 标签
result 标签包含一个标签

. fields: 用于存储字段信息，在 fields 标签下存在 field 标签，field 标签用于存储字段数据信息。
. fieldName: 字段名称
. type: 字段类型，候选项有 object 、 array 、Number、String等
. extract: 提取标签，该标签存在如下几个属性
    .. step: 步骤阶段号，对应 work 标签中的 step 属性
    .. el: 取值表达式
    .. elTYpe: 取值表达式类型
. properties: 属性集合，内部是多个 fields 标签

Result 标签的作用：定义处理结果，顶层 fields 标签用于框定有多少个属性，field 标签用于定义一个属性值相关信息。


== Flow 标签
flow 标签包含 work 标签和 watcher 标签，下面对标签进行介绍。

. flow 标签定义了一个工作流程，只存在一个属性 id 在 flow 集合中需要唯一。
. work 标签定义了工作内容，通过 ref_id 指向需要执行的 action ，step 属性表示这是第几个工作流程，需要认为定义。

在 work 标签下通过 watcher 标签对 work 标签执行后的数据进行条件判断，当条件判断满足时执行 then 标签下的 work 标签，当条件判断不满足时执行 cat 标签下的 work 标签， watcher 标签属性如下。

. condition: 条件表达式，条件表达式允许多个条件的组合，例如 true || (false && true) 。
. elType: 取值表达式类型。

[NOTE]
====
在 condition 属性编写时需要注意以下几点:

. 如果存在多个条件表达式需要将组与组之间使用小括号 `()` 进行包裹区分，并使用与 `&&` 或 `||` 进行链接。
. condition 中的取值表达式只允许出现一种，出现的表达式默认采用 JSON_PATH 编写，

====

