[#xml-design-notes]
= Action Flow XML Design Notes



:reproducible:
:listing-caption: Listing
:source-highlighter: rouge
:toc:
:toc-title: Action Flow XML Design Notes Table of Contents


Doc Writer https://github.com/brick-team[brick-team]



In a common JAVA project there are usually several actions to complete a certain business.

. Get the parameters.
. Parameter conversion (assembling the parameters of a certain business method, RPC request parameters)
. Executing an action (function, RPC call, etc.)
. Logical processing (execute XXX when XXX condition is met)
. Assemble the result information

According to the above operation flow first design the basic XML structure, the specific example is as follows

[source,xml]
----
<action-flow>
    <actions>
        <action id="rest_api_1" type="rest_api" url="" method="">
            <param in="body" name="" require="true" value="">
                <extract fromAction="" el="" elType=""/>
            </param>

            <param in="header" name="" require="true" value="">
                <extract fromAction="" el="" elType=""/>
            </param>
        </action
        <action id="java_method_1" type="java_method" className="" method="">
            <param index="0" type="java.lang.String" name="" value=""/>
        </action
    </actions

    <results
        <result flowId="1">
            <fields
                <field id="111">
                    <fieldName>O1</fieldName>
                    <type>object</type
                    <extract el="$.name" step="1"/>
                    <properties
                        <fields>
                            <field
                                <fieldName>f1</fieldName>
                                <type>String</type
                                <extract el="" step="" elType=""/>
                            </field>
                            <field
                                <fieldName>f2</fieldName>
                                <type>object</type
                                <extract el="" step="" elType=""/>
                                <properties
                                    <fields>
                                        <field
                                            <fieldName>f3</fieldName>
                                            <type>String</type
                                            <extract el="" step="" elType=""/>
                                        </field>
                                        <field
                                            <fieldName>f4</fieldName>
                                            <type>Integer</type
                                            <extract el="" step="" elType=""/>
                                        </field>
                                    </fields>
                                </properties>

                            </field>
                        </fields>
                    </properties>
                </field>


            </fields>
        </result>
    </results>

    <flows
        <flow id="1">
            <work step="1" ref_id="rest_api_1">
                <watcher condition="($.age>10)" elType="">
                    <then
                        <work step="2" ref_id="java_method_1"/>
                        <work step="3" ref_id="java_method_1"/>
                    </then
                    <cat
                        <work step="4" ref_id="java_method_1"/>
                        <work step="5" ref_id="java_method_1"/>
                    </cat
                </watcher>
            </work
        </flow>
    </flows>


</action-flow>
----

A variety of tags appear in the XML document and will be analyzed later.

== Action tags
The action tag contains multiple attributes:

. id: unique identifier
. type: type, candidates are JAVA_METHOD, REST_API
. url: routing address, type is required when REST_API is selected
. method: request method or Java method name, type select REST_API means request method (GET, POST, DELETE, PUT), type select JAVA_METHOD means Java method name
. className: Full class name, required when JAVA_METHOD is selected as the type

The action tag also contains the param tag, which is used for parameter configuration, when the type attribute of the action tag is REST_API param tag contains the following properties:

. in: the location of the parameters, candidates: body, header, query, formData, urlPath
. name: the name of the parameter
. require: required or not
. value: the default value of the request

The above solution can only support default value related parameter passing, it cannot support extracting data value from an action or extracting from a string, so the extract tag is designed to extract the parameter value, extract contains the following properties.

. fromAction: The action from which the data originates, filled in with the id attribute of the action tag. Optional, when filled, call the action tag process to get the data and then extract the value, when not filled, get from the flow tag execution parameters.
. el: The value expression, written as a JSON_PATH expression by default.
. elType: The type of the fetch expression, the project supports JSON_PATH by default.


When the type attribute of the action tag is JAVA_METHOD, the param tag contains the following attributes:

. index: index position of the parameter, counting from 0
. type: Parameter type, the full path to the java class.
. name: the name of the parameter
. value: request default value (string representation, if it is a complex type will be deserialized by GSON tool)

Action tag role: defines an action, the action can be a REST_API call, JAVA function calls. The sub-tag param is used to define the parameter information, param tag under the existence of extract tag, extract tag is used to get data from an Action tag after the implementation of the current Action tag as the implementation parameters.

== Result tag
The result tag contains a tag

. fields: used to store field information, there is a field tag under the fields tag, the field tag is used to store field data information.
. fieldName: field name
. type: field type, candidates are object, array, Number, String, etc.
. extract: The extract tag, which has the following properties
... step: step stage number, corresponding to the step attribute in the work tag
... el: the fetch expression
... elTYpe: the type of the fetch expression
. properties: collection of properties, internally multiple fields tags

Result tags are used to define the result of processing, the top-level fields tag is used to frame how many properties there are, and the fields tag is used to define information about the value of a property.


== Flow Tags
The flow tag contains the work tag and the watcher tag, which are described below.

. The flow tag defines a workflow with only one attribute id that needs to be unique in the flow collection.
. The work tag defines the content of the work and refers to the action to be executed by ref_id, and the step attribute indicates how many workflows this is and needs to be defined.

Under the work tag, the watcher tag makes a conditional judgment on the data after the work tag is executed, and the work tag under the then tag is executed when the condition is satisfied, and the work tag under the cat tag is executed when the condition is not satisfied.

. condition: A conditional expression that allows multiple combinations of conditions, such as true || (false && true).
. elType: the type of the fetch expression.

[NOTE]
====
The following points should be noted when writing the condition property:

. If there are multiple conditional expressions, use parentheses `()` to wrap them and link them with `&&` or `||`.
. Only one type of expression is allowed in condition, and by default the expressions that appear are written in JSON_PATH

====

